### ISSUE TITLE
Stash sorting

### ISSUE THREAD

**Issue by nymann** [nymann/Stashie#2]
It should be possible to sort stashes on the fly. Sorting could fx. be implemented as dividing the total space on a tab with the number of different item types. So let's say that we have 4 different item types in a tab then the space for each item could be:

<p align="center"> 
<img src="http://overseer.co/Stashie/sortingsuggestion.png">
</p>

Priority 7/10

**Comment by Treasure-Box** [comment]
I support the implementation of this, because i am a lazy sob.
