### ISSUE TITLE
char starts running aruond

### ISSUE THREAD

**Issue by Smeagol001** [nymann/Stashie#26]
when i try to sort my inventory  at some point my char starts running arund and interacting with things like my masters or the benches and stop sorting item it even sorts items in tabs i havent specified

in the config ialog of poehud ther is no way to get the list with tabs scrolled right? i have way more tabs  than are displayed (~60) how can i use the tabs that arent showen?

**Comment by zaafar** [comment]
It's working fine on my side.
Let us know if this issue is still valid. closing it for now.
