### ISSUE TITLE
New Option for extra delay in Map Stash Tab

### ISSUE THREAD

**Issue by KhaliDAlNassaj** [nymann/Stashie#30]
Its possible add a "extra delay in selected tabs?" or ONLY when store Maps and Fragments?

Cause Map tab from GGG have a bit delay when try to store different maps from different tiers at same time.
If i try to add extra global delay it works well but then store all items so much slow.
Will be awesome just "extra delay on selected tabs" cause players will can select from "list" what tabs want add this delay and not global.

If have any question please contact with me!

**Comment by zaafar** [comment]
That’s just latency issue on your side. Basically each sub tab in map stash tab is a stash tab itself. So every time you drop map into one of the sub tabs, poe client get the data from the server.




I use delay as 50ms and map stash tab works perfectly.

**Comment by zaafar** [comment]
Sleep based on inventory type....
I will try to implement that.

At what delay everything works perfectly?

**Comment by KhaliDAlNassaj** [comment]
With 50ms on MapTab seems work better.

But do you can add option to add extra delay for selected tabs with selector like extra delay you have already?

Then we can select wich tabs we want add this second extra delay.
Is a idea, you know how to do it better i asume.

**Comment by RockyBelBoar** [comment]
ignore card & map stash on plugin, response time from server is totally random.
