### ISSUE TITLE
Chisel Recipe

### ISSUE THREAD

**Issue by github23leech** [nymann/Stashie#31]
>"Chisel Recipe:\t\tBaseName=Stone Hammer|BaseName=Rock Breaker,ItemQuality=20\t:Vendor Recipes\r\n"

This won't work for Gavel since the BaseName is empty.

**Comment by zaafar** [comment]
I don’t think this plugin looks at the strength....ever....

**Comment by zaafar** [comment]
I will check the basename of Gavel.

**Comment by zaafar** [comment]
fixed, use the latest poehud.
