### ISSUE TITLE
PoeHud crashes after trying to match the items

### ISSUE THREAD

**Issue by thedot80** [nymann/Stashie#38]
PoeHud runs perfectly. I created a folder and named it stashie and copied my stuff inside. Then when I start the stashie in poeHud I see all the settings. When I try to match my stash tabs to the right items, it says stashie not working so I should move one or another stash tab to be able to use them. When I do this and go back to the settings and click to one of the buttons for matching the stash tabs, my PoEHud crashes.

**Comment by zaafar** [comment]
poehud offsets were incorrect, download latest version of poehud and the stashie. its fixed now.
