### ISSUE TITLE
Divination Bug

### ISSUE THREAD

**Issue by nartaki** [nymann/Stashie#39]
Whenever there is a divination card to place into Divination stash it miss clicks and starts clicking on the screen for remaining items left,thus leading to all sorts of unwanted clicks...

**Comment by zaafar** [comment]
just tested it, looks like div stash tab and div card is working fine.
kindly try again with latest release of poehud and this plugin.
Also, if possible, make a video if u are able to reproduce it.
you can privately send me the video if you want.

**Comment by nartaki** [comment]
Just ran into it after running the latest commit of the Hud. Will try and replicate and send you a video

**Comment by zaafar** [comment]
What’s your delay value? This looks like your delay is really really low.

**Comment by zaafar** [comment]
Okay, try this.


Put div stash tab in first 1st or 2nd or 3rd tabs and reduce it's name to something small, like "div" or "d".
let me know if this fixes the issue.

**Comment by zaafar** [comment]
ignore my previous post. Basically if you move your tab, you need to do an area change, otherwise stashie won't work properly. So when you hit the issue, did you move your stash tab????

**Comment by zaafar** [comment]
btw make sure your stashie isn't conflicting with trade macro plugin...

**Comment by zaafar** [comment]
Basically run stashie and poehud without the trade macro ( or any auto hotkey program ) running in the background.

**Comment by nartaki** [comment]
Hey sorry for the late reply,tbh i did get the issue once but im unsure if both hud and stashie were updated to their latest versions.I have been playing lightly for a week without the issue occuring at all. Keep it open for a few more days so i can really test it out with all variables in mind.

P.S been running trademacro alongside with it and seems the error was not related to the two programs running alongside.

**Comment by zaafar** [comment]
Nah, ms shouldn’t effect such things....

**Comment by nartaki** [comment]
Now something funny happened,i replicated the error and it was like some key was being held,i had to alt+ctrl+del and then click on PoE again to make my kb function...

**Comment by nartaki** [comment]
Ok..I totally deleted hud folder and downloaded again,installed only Plugin Updater and installed my preferred plugins from there. Now its just happening all the time. Not running TradeMacro or Ahk at all. Only running Stashie as plugin.I will migrate to another version of windows and report again in a couple days. Sorry for keeping you on this..

**Comment by nartaki** [comment]
Have been playing on standard for a while now and have not run into the issue .I believe this can close now.
