### ISSUE TITLE
Stuck Mouse cursor Hovering over empty cell after stashing items 

### ISSUE THREAD

**Issue by Arecurius0** [nymann/Stashie#53]
The mouse cursor is stuck on the first cell of the player inventory after stashing items

**Comment by nymann** [comment]
Macaddict via Discord:
> i think it happens when the last item gets moved into stash, the memory cache hasn't updated yet and still thinks there's an item in your bag
so it tries to mouse over the last item and it's waiting for hover to not be null
but it is, because the item's been moved
could be improved by checking that hover is null after clicking before moving to the next item

**Comment by Arecurius0** [comment]
"fixed" with the latest refactoring update by disabling the whole hover item null check. Seems unnecessary at this point. So far stashie runs very smooth without it.
