### ISSUE TITLE
Ability to add names to tabs on tab list.

### ISSUE THREAD

**Issue by NoNick96** [nymann/Stashie#62]
I would love to see a feature that adds an overlay onto the tab list which allows assigning custom names for each tab.

**Comment by Arecurius0** [comment]
i just read your comment explaining what your request is on ownedcore and im sorry but for my unerstanding this would not belong in this plugin as it does not interact with the stashes itself and the stashing process done by stashie. You could however just make your own simple plugin that fullfills your needs. Drawing some text in a transparent manner onto existing UI elements does not sound hard at all and could probably be done in under 500 loc.
But whats your opinion @nymann ?
