### ISSUE TITLE
Will not pick items.

### ISSUE THREAD

**Issue by V4mpyr** [nymann/Stashie#67]
I use stashie, with great success but sometimes it breaks and the cursor just goes to the bottom left of the screen for a few seconds and doesn't select items. It's on a standard resolution full screen and windowed full screen. I am using the latest hud, which i assumed the latest updates are pushed to it.. so I'm sure how to fix this. Stashie is a HUGE Qol that i am struggling without.

kind regards,

**Comment by Arecurius0** [comment]
Likely an issue with your settings or the hud your using. Try increasing delays in Stashie's Settings

**Comment by nymann** [comment]
@V4mpyr let us know if you keep having issues.

**Comment by V4mpyr** [comment]
Hey boys, 

Yeah really weird interaction, I've only seen it when a new patch is released and offsets need updated. 

Essentially I when I hit hotkey (default) it shuffles tabs goes to the starting tab position and instead of selecting items in my inventory it goes all the way to the right side of screen stalls for a min and released my cursor. Nothing gets moved to my inventory obviously when it does that. 

I just tested without any other programs running and it seemed to work fine without any trouble. Currently I am using an auto flasker using AHK and Cheat Engine for zoom/mh. I wouldn't think these would interfere with it. The hotkeys are changed so that they do not conflict with any that of the flasker is using.

**Comment by Arecurius0** [comment]
ye broken offsets cause plugins to possibly not work as intended
